/** Generated by DesignDNA — brand: pinterest */
export const tokens = {
  "brand": "pinterest",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "pinterest-red": "#e60023",
    "green-700": "#103c25",
    "green-700-hover": "#0b2819",
    "plum-black": "#211922",
    "black": "#000000",
    "olive-gray": "#62625b",
    "warm-silver": "#91918c",
    "white": "#ffffff",
    "focus-blue": "#435ee5",
    "performance-purple": "#6845ab",
    "recommendation-purple": "#7e238b",
    "link-blue": "#2b48d4",
    "facebook-blue": "#0866ff",
    "pressed-blue": "#617bff",
    "sand-gray": "#e5e5e0",
    "warm-light": "#e0e0d9",
    "fog": "#f6f6f3",
    "border-disabled": "#c8c8c1",
    "hover-gray": "#bcbcb3",
    "dark-surface": "#33332e",
    "error-red": "#9e0a0a"
  },
  "typography": {
    "families": [
      "Black",
      "White",
      "Primary"
    ],
    "sizes": {
      "large": "28px",
      "hero": "40px"
    },
    "weights": [
      400,
      600
    ]
  },
  "spacing": {
    "space-1": "6px",
    "space-2": "16px"
  },
  "radius": {
    "radius-1": "16px"
  },
  "shadows": {
    "shadow-1": "on most cards"
  }
} as const;

export type DesignTokens = typeof tokens;
