/** Generated by DesignDNA — brand: zapier */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "zapier-black": "#201515",
        "cream-white": "#fffefb",
        "off-white": "#fffdf9",
        "zapier-orange": "#ff4f00",
        "dark-charcoal": "#36342e",
        "warm-gray": "#939084",
        sand: "#c5c0b1",
        "light-sand": "#eceae3",
        "mid-warm": "#b5b2aa"
      },
      fontFamily: {
        sans: [
          "Degular Display",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Inter",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Off-White",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Sand",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        display: "80px"
      },
      borderRadius: {
        "radius-1": "4px",
        "radius-2": "8px",
        "radius-3": "20px",
        "radius-4": "5px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "0.48px",
        "space-2": "1.6px",
        "space-3": "8px",
        "space-4": "12px",
        "space-5": "20px",
        "space-6": "60px",
        "space-7": "64px",
        "space-8": "80px"
      }
    }
  }
};
