/** Generated by DesignDNA — brand: bmw */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "pure-white": "#ffffff",
        "bmw-blue": "#1c69d4",
        "bmw-focus-blue": "#0653b6",
        "near-black": "#262626",
        "meta-gray": "#757575",
        silver: "#bbbbbb"
      },
      fontFamily: {
        sans: [
          "in two variants",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "at different weights",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Silver",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "60px"
      },
      borderRadius: {},
      boxShadow: {},
      spacing: {}
    }
  }
};
