/** Generated by DesignDNA — brand: figma */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "pure-black": "#000000",
        "pure-white": "#ffffff"
      },
      fontFamily: {
        sans: [
          "Primary",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {
        "radius-1": "6px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "0.1px",
        "space-2": "0.14px",
        "space-3": "0.54px",
        "space-4": "0.96px",
        "space-5": "1.72px",
        "space-6": "8px"
      }
    }
  }
};
