/** Generated by DesignDNA — brand: sentry */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "deep-purple": "#1f1633",
        "darker-purple": "#150f23",
        "border-purple": "#362d59",
        "sentry-purple": "#6a5fc1",
        "muted-purple": "#79628c",
        "deep-violet": "#422082",
        "lime-green": "#c2ef4e",
        coral: "#ffb287",
        pink: "#fa7faa",
        "pure-white": "#ffffff",
        "light-gray": "#e5e7eb",
        "code-yellow": "#dcdcaa",
        "input-border": "#cfcfdb"
      },
      fontFamily: {
        sans: [
          "Coral",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Pink",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Display",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Primary UI",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {
        "radius-1": "13px",
        "radius-2": "12px",
        "radius-3": "8px",
        "radius-4": "6px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "0.2px",
        "space-2": "2rem",
        "space-3": "4rem",
        "space-4": "8px",
        "space-5": "12px",
        "space-6": "64px"
      }
    }
  }
};
