/** Generated by DesignDNA — brand: nvidia */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "nvidia-green": "#76b900",
        "true-black": "#000000",
        "pure-white": "#ffffff",
        "nvidia-green-light": "#bff230",
        "orange-400": "#df6500",
        "yellow-300": "#ef9100",
        "yellow-050": "#feeeb2",
        "red-500": "#e52020",
        "red-800": "#650b0b",
        "green-500": "#3f8500",
        "blue-700": "#0046a4",
        "purple-800": "#4d1368",
        "purple-100": "#f9d4ff",
        "fuchsia-700": "#8c1c55",
        "gray-300": "#a7a7a7",
        "gray-400": "#898989",
        "gray-500": "#757575",
        "gray-border": "#5e5e5e",
        "near-black": "#1a1a1a",
        "link-hover": "#3860be",
        "button-hover": "#1eaedb",
        "button-active": "#007fff",
        "muted-links": "#666666"
      },
      fontFamily: {
        sans: [
          "Primary",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "36px",
        display: "36px"
      },
      borderRadius: {
        "radius-1": "2px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "0.144px",
        "space-2": "8px",
        "space-3": "11px",
        "space-4": "24px",
        "space-5": "80px"
      }
    }
  }
};
