/** Generated by DesignDNA — brand: webflow */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "near-black": "#080808",
        "webflow-blue": "#146ef5",
        "blue-400": "#3b89ff",
        "blue-300": "#006acc",
        "button-hover-blue": "#0055d4",
        purple: "#7a3dff",
        pink: "#ed52cb",
        green: "#00d722",
        orange: "#ff6b00",
        yellow: "#ffae13",
        red: "#ee1d36",
        "gray-800": "#222222",
        "gray-700": "#363636",
        "gray-300": "#ababab",
        "mid-gray": "#5a5a5a",
        "border-gray": "#d8d8d8",
        "border-hover": "#898989"
      },
      fontFamily: {
        sans: [
          "Purple",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Pink",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Green",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Orange",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "80px",
        body: "20px",
        caption: "14px"
      },
      borderRadius: {
        "radius-1": "2px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "0.6px",
        "space-2": "1px"
      }
    }
  }
};
