/** Generated by DesignDNA — brand: sanity */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "sanity-black": "#0b0b0b",
        "pure-black": "#000000",
        "sanity-red": "#f36458",
        "electric-blue": "#0052ef",
        "light-blue": "#55beff",
        "dark-gray": "#212121",
        "medium-dark": "#353535",
        "pure-white": "#ffffff",
        "light-gray": "#ededed",
        silver: "#b9b9b9",
        "medium-gray": "#797979",
        "error-red": "#dd0000",
        "gpc-green": "#37cd84"
      },
      fontFamily: {
        sans: [
          "White",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Silver",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Charcoal",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Footer",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {
        "radius-1": "99999px",
        "radius-2": "5px",
        "radius-3": "6px",
        "radius-4": "12px",
        "radius-5": "3px"
      },
      boxShadow: {
        "shadow-1": "s -- ring shadows (0 0 0 Npx) or border-based containment only"
      },
      spacing: {
        "space-1": "0.32px",
        "space-2": "2px",
        "space-3": "2.88px",
        "space-4": "8px",
        "space-5": "13px",
        "space-6": "16px",
        "space-7": "24px",
        "space-8": "32px",
        "space-9": "48px",
        "space-10": "120px"
      }
    }
  }
};
