/** Generated by DesignDNA — brand: tesla */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "electric-blue": "#3e6ae1",
        "pure-white": "#ffffff",
        "light-ash": "#f4f4f4",
        "carbon-dark": "#171a20",
        graphite: "#393c41",
        pewter: "#5c5e62",
        "silver-fog": "#8e8e8e",
        "cloud-gray": "#eeeeee",
        "pale-silver": "#d0d1d2"
      },
      fontFamily: {
        sans: [
          "should speak for itself without",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "at different sizes",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Universal Sans Text",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Graphite",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {
        "radius-1": "4px"
      },
      boxShadow: {
        "shadow-1": "transition",
        "shadow-2": "0.33s cubic-bezier(0.5, 0, 0, 0.75), color 0.33s",
        "shadow-3": "s entirely in its primary interface. Depth is communicated through three alternative strategies:"
      },
      spacing: {
        "space-1": "4px",
        "space-2": "16px"
      }
    }
  }
};
