/** Generated by DesignDNA — brand: claude */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "anthropic-near-black": "#141413",
        "terracotta-brand": "#c96442",
        "coral-accent": "#d97757",
        "error-crimson": "#b53333",
        "focus-blue": "#3898ec",
        parchment: "#f5f4ed",
        ivory: "#faf9f5",
        "pure-white": "#ffffff",
        "warm-sand": "#e8e6dc",
        "dark-surface": "#30302e",
        "charcoal-warm": "#4d4c48",
        "olive-gray": "#5e5d59",
        "stone-gray": "#87867f",
        "dark-warm": "#3d3d3a",
        "warm-silver": "#b0aea5",
        "border-cream": "#f0eee6",
        "ring-warm": "#d1cfc5",
        "ring-subtle": "#dedc01",
        "ring-deep": "#c2c0b6"
      },
      fontFamily: {
        sans: [
          "Parchment",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Ivory",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Headline",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Code",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {},
      boxShadow: {},
      spacing: {
        "space-1": "0.12px",
        "space-2": "1.6px",
        "space-3": "8px",
        "space-4": "9.6px",
        "space-5": "12px",
        "space-6": "16px",
        "space-7": "32px",
        "space-8": "120px"
      }
    }
  }
};
