/** Generated by DesignDNA — brand: linear.app */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "dark-mode-native": "#08090a",
        "brand-indigo-violet": "#5e6ad2",
        "marketing-black": "#010102",
        "panel-dark": "#0f1011",
        "level-3-surface": "#191a1b",
        "secondary-surface": "#28282c",
        "primary-text": "#f7f8f8",
        "secondary-text": "#d0d6e0",
        "tertiary-text": "#8a8f98",
        "quaternary-text": "#62666d",
        "accent-violet": "#7170ff",
        "accent-hover": "#828fff",
        "security-lavender": "#7a7fad",
        green: "#27a644",
        emerald: "#10b981",
        "border-primary": "#23252a",
        "border-secondary": "#34343a",
        "border-tertiary": "#3e3e44",
        "line-tint": "#141516",
        "line-tertiary": "#18191a",
        "light-surface": "#f3f4f5",
        "light-border-alt": "#e6e6e6",
        "pure-white": "#ffffff",
        text: "#e2e4e7"
      },
      fontFamily: {
        sans: [
          "identity",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Primary Text",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Secondary Text",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Tertiary Text",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        large: "22px",
        hero: "72px"
      },
      borderRadius: {
        "radius-1": "6px",
        "radius-2": "9999px",
        "radius-3": "2px",
        "radius-4": "8px",
        "radius-5": "5px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "0.165px",
        "space-2": "0.24px",
        "space-3": "1px",
        "space-4": "1.056px",
        "space-5": "1.584px",
        "space-6": "6px",
        "space-7": "8px",
        "space-8": "12px",
        "space-9": "80px"
      }
    }
  }
};
