/** Generated by DesignDNA — brand: framer */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "pure-black": "#000000",
        "pure-white": "#ffffff",
        "framer-blue": "#0099ff",
        "muted-silver": "#a6a6a6",
        "near-black": "#090909",
        "default-link-blue": "#0000ee"
      },
      fontFamily: {
        sans: [
          "Display",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Accent",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Monospace",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Rounded",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        display: "85px"
      },
      borderRadius: {},
      boxShadow: {},
      spacing: {
        "space-1": "3px",
        "space-2": "5.5px",
        "space-3": "8px",
        "space-4": "10px",
        "space-5": "15px",
        "space-6": "44px",
        "space-7": "80px",
        "space-8": "120px"
      }
    }
  }
};
