/** Generated by DesignDNA — brand: notion */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "pure-white": "#ffffff",
        "notion-blue": "#0075de",
        "deep-navy": "#213183",
        "active-blue": "#005bab",
        "warm-white": "#f6f5f4",
        "warm-dark": "#31302e",
        "warm-gray-500": "#615d59",
        "warm-gray-300": "#a39e98",
        teal: "#2a9d99",
        green: "#1aae39",
        orange: "#dd5b00",
        pink: "#ff64c8",
        purple: "#391c57",
        brown: "#523410",
        "link-light-blue": "#62aef0",
        "focus-blue": "#097fe8",
        "badge-blue-bg": "#f2f9ff",
        text: "#000000"
      },
      fontFamily: {
        sans: [
          "Teal",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Green",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Orange",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Pink",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        body: "16px",
        large: "16px",
        hero: "64px"
      },
      borderRadius: {
        "radius-1": "4px",
        "radius-2": "9999px",
        "radius-3": "12px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "0.125px",
        "space-2": "0.25px",
        "space-3": "1.5px",
        "space-4": "2.125px",
        "space-5": "4px",
        "space-6": "6px",
        "space-7": "8px",
        "space-8": "12px",
        "space-9": "64px",
        "space-10": "80px"
      }
    }
  }
};
