/** Generated by DesignDNA — brand: airtable */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "deep-navy": "#181d26",
        "airtable-blue": "#1b61c9",
        white: "#ffffff",
        "success-green": "#006400",
        "dark-gray": "#333333",
        "mid-blue": "#254fad",
        border: "#e0e2e6",
        "light-surface": "#f8fafc"
      },
      fontFamily: {
        sans: [
          "White",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Spotlight",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Weak Text",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Border",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        small: "12px"
      },
      borderRadius: {
        "radius-1": "2px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "0.08px",
        "space-2": "12px",
        "space-3": "48px"
      }
    }
  }
};
