/** Generated by DesignDNA — brand: mintlify */
export const tokens = {
  "brand": "mintlify",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "near-black": "#0d0d0d",
    "pure-white": "#ffffff",
    "brand-green": "#18e299",
    "brand-green-light": "#d4fae8",
    "brand-green-deep": "#0fa76e",
    "warm-amber": "#c37d0d",
    "soft-blue": "#3772cf",
    "error-red": "#d45656",
    "gray-700": "#333333",
    "gray-500": "#666666",
    "gray-400": "#888888",
    "gray-200": "#e5e5e5",
    "gray-100": "#f5f5f5",
    "gray-50": "#fafafa",
    "text-primary": "#ededed",
    "text-secondary": "#a0a0a0",
    "card-background": "#141414"
  },
  "typography": {
    "families": [
      "Inter 15px weight 500",
      "Primary",
      "Monospace",
      "Background"
    ],
    "sizes": {
      "large": "24px",
      "hero": "64px"
    },
    "weights": [
      400,
      500,
      600
    ]
  },
  "spacing": {
    "space-1": "0.2px",
    "space-2": "0.8px",
    "space-3": "1px",
    "space-4": "1.28px",
    "space-5": "4.5px",
    "space-6": "5px",
    "space-7": "8px",
    "space-8": "13px",
    "space-9": "24px",
    "space-10": "32px"
  },
  "radius": {
    "radius-1": "9999px",
    "radius-2": "8px",
    "radius-3": "16px",
    "radius-4": "24px"
  },
  "shadows": {}
} as const;

export type DesignTokens = typeof tokens;
