/** Generated by DesignDNA — brand: minimax */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "brand-blue": "#1456f0",
        "sky-blue": "#3daeff",
        "brand-pink": "#ea5ec1",
        "primary-200": "#bfdbfe",
        "primary-light": "#60a5fa",
        "primary-500": "#3b82f6",
        "primary-600": "#2563eb",
        "primary-700": "#1d4ed8",
        "brand-deep": "#17437d",
        "near-black": "#222222",
        dark: "#18181b",
        charcoal: "#181e25",
        "dark-gray": "#45515e",
        "mid-gray": "#8e8e93",
        "light-gray": "#5f5f5f",
        "pure-white": "#ffffff",
        "border-light": "#f2f3f5",
        "border-gray": "#e5e7eb",
        "success-background": "#e8ffea",
        background: "#f0f0f0",
        text: "#333333"
      },
      fontFamily: {
        sans: [
          "DM Sans serves as the primary UI",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Dark",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Charcoal",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Standard",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        large: "22px",
        hero: "80px"
      },
      borderRadius: {
        "radius-1": "8px",
        "radius-2": "9999px",
        "radius-3": "20px",
        "radius-4": "13px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "11px",
        "space-2": "16px",
        "space-3": "40px",
        "space-4": "64px",
        "space-5": "80px"
      }
    }
  }
};
