/** Generated by DesignDNA — brand: miro */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "near-black": "#1c1c1e",
        white: "#ffffff",
        "blue-450": "#5b76fe",
        "actionable-pressed": "#2a41b6",
        coral: "#ffc6c6",
        rose: "#ffd8f4",
        teal: "#c3faf5",
        orange: "#ffe6cd",
        yellow: "#746019",
        moss: "#187574",
        pink: "#fde0f0",
        red: "#fbd4d4",
        "dark-red": "#e3c5c5",
        success: "#00b473",
        slate: "#555a6a",
        "input-placeholder": "#a5a8b5",
        border: "#c7cad5"
      },
      fontFamily: {
        sans: [
          "White",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Coral",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Rose",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Teal",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {
        "radius-1": "8px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "24px"
      }
    }
  }
};
