/** Generated by DesignDNA — brand: stripe */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "stripe-purple": "#533afd",
        "deep-navy": "#061b31",
        "pure-white": "#ffffff",
        "brand-dark": "#1c1e54",
        "dark-navy": "#0d253d",
        ruby: "#ea2261",
        magenta: "#f96bee",
        "magenta-light": "#ffd7ef",
        "purple-hover": "#4434d4",
        "purple-deep": "#2e2b8c",
        "purple-light": "#b9b9f9",
        "purple-mid": "#665efd",
        label: "#273951",
        body: "#64748d",
        "success-green": "#15be53",
        "success-text": "#108c3d",
        lemon: "#9b6829",
        "border-default": "#e5edf5",
        "border-soft-purple": "#d6d9fc",
        "border-dashed": "#362baa",
        text: "#2874ad"
      },
      fontFamily: {
        sans: [
          "Ruby",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Magenta",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Heading",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Label",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "56px",
        display: "32px",
        body: "16px"
      },
      borderRadius: {
        "radius-1": "4px",
        "radius-2": "6px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "0.22px",
        "space-2": "0.64px",
        "space-3": "0.96px",
        "space-4": "1px",
        "space-5": "1.4px",
        "space-6": "8px",
        "space-7": "10px",
        "space-8": "64px"
      }
    }
  }
};
