/** Generated by DesignDNA — brand: supabase */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "supabase-green": "#3ecf8e",
        "green-link": "#00c573",
        "near-black": "#0f0f0f",
        dark: "#171717",
        "dark-border": "#242424",
        "border-dark": "#2e2e2e",
        "mid-border": "#363636",
        "border-light": "#393939",
        charcoal: "#434343",
        "dark-gray": "#4d4d4d",
        "mid-gray": "#898989",
        "light-gray": "#b4b4b4",
        "near-white": "#efefef",
        "off-white": "#fafafa"
      },
      fontFamily: {
        sans: [
          "almost no shadows",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Dark",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Charcoal",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Purple",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        large: "16px",
        hero: "72px"
      },
      borderRadius: {
        "radius-1": "9999px",
        "radius-2": "6px",
        "radius-3": "8px"
      },
      boxShadow: {
        "shadow-1": "s. Focus states use"
      },
      spacing: {
        "space-1": "0.16px",
        "space-2": "1px",
        "space-3": "1.2px",
        "space-4": "8px",
        "space-5": "16px",
        "space-6": "90px",
        "space-7": "128px"
      }
    }
  }
};
