/** Generated by DesignDNA — brand: supabase */
export const tokens = {
  "brand": "supabase",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "supabase-green": "#3ecf8e",
    "green-link": "#00c573",
    "near-black": "#0f0f0f",
    "dark": "#171717",
    "dark-border": "#242424",
    "border-dark": "#2e2e2e",
    "mid-border": "#363636",
    "border-light": "#393939",
    "charcoal": "#434343",
    "dark-gray": "#4d4d4d",
    "mid-gray": "#898989",
    "light-gray": "#b4b4b4",
    "near-white": "#efefef",
    "off-white": "#fafafa"
  },
  "typography": {
    "families": [
      "almost no shadows",
      "Dark",
      "Charcoal",
      "Purple"
    ],
    "sizes": {
      "large": "16px",
      "hero": "72px"
    },
    "weights": [
      400,
      500
    ]
  },
  "spacing": {
    "space-1": "0.16px",
    "space-2": "1px",
    "space-3": "1.2px",
    "space-4": "8px",
    "space-5": "16px",
    "space-6": "90px",
    "space-7": "128px"
  },
  "radius": {
    "radius-1": "9999px",
    "radius-2": "6px",
    "radius-3": "8px"
  },
  "shadows": {
    "shadow-1": "s. Focus states use"
  }
} as const;

export type DesignTokens = typeof tokens;
