/** Generated by DesignDNA — brand: warp */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "warm-parchment": "#faf9f6",
        "earth-gray": "#353534",
        "stone-gray": "#868584",
        "ash-gray": "#afaeac",
        "purple-tint-gray": "#666469",
        "dark-charcoal": "#454545"
      },
      fontFamily: {
        sans: [
          "Medium",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Square",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Monospace Display",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Ghost",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        display: "56px"
      },
      borderRadius: {},
      boxShadow: {},
      spacing: {
        "space-1": "0.4px",
        "space-2": "1.4px",
        "space-3": "2.4px",
        "space-4": "8px",
        "space-5": "16px",
        "space-6": "80px"
      }
    }
  }
};
