/** Generated by DesignDNA — brand: mongodb */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "forest-black": "#001e2b",
        "mongodb-green": "#00ed64",
        "dark-green": "#00684a",
        "action-blue": "#006cfa",
        "hover-blue": "#3860be",
        "teal-active": "#1eaedb",
        "deep-teal": "#1c2d38",
        "teal-gray": "#3d4f58",
        "dark-slate": "#21313c",
        "cool-gray": "#5c6c75",
        "silver-teal": "#b8c4c2",
        "light-input": "#e8edeb",
        "pure-white": "#ffffff",
        black: "#000000"
      },
      fontFamily: {
        sans: [
          "Black",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Display Serif",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Fallbacks",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        large: "24px",
        hero: "48px"
      },
      borderRadius: {
        "radius-1": "100px",
        "radius-2": "4px",
        "radius-3": "16px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "1px",
        "space-2": "2px",
        "space-3": "12px",
        "space-4": "80px"
      }
    }
  }
};
