/** Generated by DesignDNA — brand: kraken */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "kraken-purple": "#7132f5",
        "purple-dark": "#5741d8",
        "purple-deep": "#5b1ecf",
        "near-black": "#101114",
        "cool-gray": "#686b82",
        "silver-blue": "#9497a9",
        white: "#ffffff",
        "border-gray": "#dedee5",
        green: "#149e61",
        "green-dark": "#026b3f"
      },
      fontFamily: {
        sans: [
          "White",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Green",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Display",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {
        "radius-1": "12px",
        "radius-2": "10px",
        "radius-3": "3px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "1px",
        "space-2": "8px",
        "space-3": "13px"
      }
    }
  }
};
