/** Generated by DesignDNA — brand: ferrari */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "ferrari-red": "#da291c",
        "pure-white": "#ffffff",
        "dark-red": "#b01e0a",
        "deep-red": "#9d2211",
        "racing-yellow": "#fff200",
        "modena-yellow": "#f6e500",
        "absolute-black": "#000000",
        "dark-surface": "#303030",
        "light-gray-surface": "#d2d2d2",
        "near-black": "#181818",
        "dark-gray": "#666666",
        "mid-gray": "#8f8f8f",
        "silver-gray": "#969696",
        "warning-red": "#f13a2c",
        "success-green": "#03904a",
        "info-blue": "#4c98b9",
        "link-hover-blue": "#3860be"
      },
      fontFamily: {
        sans: [
          "handles captions and utility tex",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "with compact proportions and med",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "for headings",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "for captions",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        caption: "13px"
      },
      borderRadius: {
        "radius-1": "2px",
        "radius-2": "8px"
      },
      boxShadow: {
        "shadow-1": "s to cards or content containers — depth comes from surface color contrast and photography"
      },
      spacing: {
        "space-1": "1px",
        "space-2": "1.28px",
        "space-3": "12px",
        "space-4": "16px",
        "space-5": "20px",
        "space-6": "25px",
        "space-7": "40px",
        "space-8": "44px",
        "space-9": "80px"
      }
    }
  }
};
