/** Generated by DesignDNA — brand: ollama */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "pure-black": "#000000",
        "near-black": "#262626",
        "darkest-surface": "#090909",
        "pure-white": "#ffffff",
        snow: "#fafafa",
        "light-gray": "#e5e5e5",
        stone: "#737373",
        "mid-gray": "#525252",
        silver: "#a3a3a3",
        "button-text-dark": "#404040",
        "ring-blue": "#3b82f6",
        "border-light": "#d4d4d4"
      },
      fontFamily: {
        sans: [
          "zero shadows",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Snow",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Stone",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Silver",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {},
      boxShadow: {},
      spacing: {
        "space-1": "10px",
        "space-2": "32px",
        "space-3": "88px"
      }
    }
  }
};
