/** Generated by DesignDNA — brand: ollama */
export const tokens = {
  "brand": "ollama",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "pure-black": "#000000",
    "near-black": "#262626",
    "darkest-surface": "#090909",
    "pure-white": "#ffffff",
    "snow": "#fafafa",
    "light-gray": "#e5e5e5",
    "stone": "#737373",
    "mid-gray": "#525252",
    "silver": "#a3a3a3",
    "button-text-dark": "#404040",
    "ring-blue": "#3b82f6",
    "border-light": "#d4d4d4"
  },
  "typography": {
    "families": [
      "zero shadows",
      "Snow",
      "Stone",
      "Silver"
    ],
    "sizes": {},
    "weights": [
      400,
      500
    ]
  },
  "spacing": {
    "space-1": "10px",
    "space-2": "32px",
    "space-3": "88px"
  },
  "radius": {},
  "shadows": {}
} as const;

export type DesignTokens = typeof tokens;
