/** Generated by DesignDNA — brand: airbnb */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "rausch-red": "#ff385c",
        "deep-rausch": "#e00b41",
        "error-red": "#c13515",
        "error-dark": "#b32505",
        "luxe-purple": "#460479",
        "plus-magenta": "#92174d",
        "near-black": "#222222",
        "focused-gray": "#3f3f3f",
        "secondary-gray": "#6a6a6a",
        "link-disabled": "#929292",
        "legal-blue": "#428bff",
        "border-gray": "#c1c1c1",
        "light-surface": "#f2f2f2",
        "pure-white": "#ffffff"
      },
      fontFamily: {
        sans: [
          "Disabled",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Primary",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        large: "32px"
      },
      borderRadius: {
        "radius-1": "8px",
        "radius-2": "14px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "0.18px"
      }
    }
  }
};
