/** Generated by DesignDNA — brand: airbnb */
export const tokens = {
  "brand": "airbnb",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "rausch-red": "#ff385c",
    "deep-rausch": "#e00b41",
    "error-red": "#c13515",
    "error-dark": "#b32505",
    "luxe-purple": "#460479",
    "plus-magenta": "#92174d",
    "near-black": "#222222",
    "focused-gray": "#3f3f3f",
    "secondary-gray": "#6a6a6a",
    "link-disabled": "#929292",
    "legal-blue": "#428bff",
    "border-gray": "#c1c1c1",
    "light-surface": "#f2f2f2",
    "pure-white": "#ffffff"
  },
  "typography": {
    "families": [
      "Disabled",
      "Primary"
    ],
    "sizes": {
      "large": "32px"
    },
    "weights": [
      300,
      400,
      500,
      600
    ]
  },
  "spacing": {
    "space-1": "0.18px"
  },
  "radius": {
    "radius-1": "8px",
    "radius-2": "14px"
  },
  "shadows": {}
} as const;

export type DesignTokens = typeof tokens;
