/** Generated by DesignDNA — brand: lovable */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "warm-neutral-border-palette": "#eceae4",
        cream: "#f7f4ed",
        charcoal: "#1c1c1c",
        "off-white": "#fcfbf8",
        "muted-gray": "#5f5f5d",
        "ring-blue": "#3b82f6"
      },
      fontFamily: {
        sans: [
          "is the system",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "carries the brand personality",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "with humanist warmth and editori",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Cream",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "60px"
      },
      borderRadius: {
        "radius-1": "6px",
        "radius-2": "9999px",
        "radius-3": "12px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "0.9px",
        "space-2": "1px",
        "space-3": "1.2px",
        "space-4": "1.5px",
        "space-5": "8px",
        "space-6": "24px",
        "space-7": "80px",
        "space-8": "96px",
        "space-9": "128px"
      }
    }
  }
};
