/** Generated by DesignDNA — brand: lovable */
export const tokens = {
  "brand": "lovable",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "warm-neutral-border-palette": "#eceae4",
    "cream": "#f7f4ed",
    "charcoal": "#1c1c1c",
    "off-white": "#fcfbf8",
    "muted-gray": "#5f5f5d",
    "ring-blue": "#3b82f6"
  },
  "typography": {
    "families": [
      "is the system",
      "carries the brand personality",
      "with humanist warmth and editori",
      "Cream"
    ],
    "sizes": {
      "hero": "60px"
    },
    "weights": [
      400,
      480,
      600,
      700
    ]
  },
  "spacing": {
    "space-1": "0.9px",
    "space-2": "1px",
    "space-3": "1.2px",
    "space-4": "1.5px",
    "space-5": "8px",
    "space-6": "24px",
    "space-7": "80px",
    "space-8": "96px",
    "space-9": "128px"
  },
  "radius": {
    "radius-1": "6px",
    "radius-2": "9999px",
    "radius-3": "12px"
  },
  "shadows": {}
} as const;

export type DesignTokens = typeof tokens;
