/** Generated by DesignDNA — brand: replicate */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "replicate-dark": "#202020",
        "replicate-red": "#ea2804",
        "secondary-red": "#dd4425",
        "status-green": "#2b9a66",
        "github-dark": "#24292e",
        "pure-white": "#ffffff",
        "near-white": "#fcfcfc",
        "medium-gray": "#646464",
        "warm-gray": "#4e4e4e",
        "mid-silver": "#8d8d8d",
        "light-silver": "#bbbbbb",
        "pure-black": "#000000"
      },
      fontFamily: {
        sans: [
          "Display",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Code",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Navigation",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Manifesto",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {},
      boxShadow: {},
      spacing: {
        "space-1": "6px",
        "space-2": "72px"
      }
    }
  }
};
