/** Generated by DesignDNA — brand: replicate */
export const tokens = {
  "brand": "replicate",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "replicate-dark": "#202020",
    "replicate-red": "#ea2804",
    "secondary-red": "#dd4425",
    "status-green": "#2b9a66",
    "github-dark": "#24292e",
    "pure-white": "#ffffff",
    "near-white": "#fcfcfc",
    "medium-gray": "#646464",
    "warm-gray": "#4e4e4e",
    "mid-silver": "#8d8d8d",
    "light-silver": "#bbbbbb",
    "pure-black": "#000000"
  },
  "typography": {
    "families": [
      "Display",
      "Code",
      "Navigation",
      "Manifesto"
    ],
    "sizes": {},
    "weights": [
      600,
      700
    ]
  },
  "spacing": {
    "space-1": "6px",
    "space-2": "72px"
  },
  "radius": {},
  "shadows": {}
} as const;

export type DesignTokens = typeof tokens;
