/** Generated by DesignDNA — brand: ibm */
export const tokens = {
  "brand": "ibm",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "ibm-blue-60": "#0f62fe",
    "white": "#ffffff",
    "gray-100": "#161616",
    "gray-90": "#262626",
    "gray-80": "#393939",
    "gray-70": "#525252",
    "gray-60": "#6f6f6f",
    "gray-50": "#8d8d8d",
    "gray-30": "#c6c6c6",
    "gray-20": "#e0e0e0",
    "gray-10": "#f4f4f4",
    "gray-10-hover": "#e8e8e8",
    "blue-70": "#0043ce",
    "blue-80": "#002d9c",
    "blue-10": "#edf5ff",
    "red-60": "#da1e28",
    "green-50": "#24a148",
    "yellow-30": "#f1c21b",
    "interactive": "#78a9ff",
    "hover": "#0353e9"
  },
  "typography": {
    "families": [
      "White",
      "Background",
      "Interactive",
      "Primary"
    ],
    "sizes": {
      "hero": "60px",
      "display": "42px"
    },
    "weights": [
      300,
      400,
      600,
      700
    ]
  },
  "spacing": {
    "space-1": "0.16px",
    "space-2": "0.32px",
    "space-3": "1px",
    "space-4": "2px",
    "space-5": "4px",
    "space-6": "8px",
    "space-7": "12px",
    "space-8": "14px",
    "space-9": "16px",
    "space-10": "20px"
  },
  "radius": {
    "radius-1": "0px",
    "radius-2": "24px"
  },
  "shadows": {}
} as const;

export type DesignTokens = typeof tokens;
