/** Generated by DesignDNA — brand: elevenlabs */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "pure-white": "#ffffff",
        "light-gray": "#f5f5f5",
        "warm-stone": "#f5f2ef",
        black: "#000000",
        "dark-gray": "#4e4e4e",
        "warm-gray": "#777169",
        "near-white": "#f6f6f6",
        "grid-cyan": "#7fffff",
        "border-light": "#e5e5e5"
      },
      fontFamily: {
        sans: [
          "WaldenburgFH 14px weight 700",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Black",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Display",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Monospace",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        large: "18px"
      },
      borderRadius: {
        "radius-1": "9999px",
        "radius-2": "30px",
        "radius-3": "16px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "0.14px",
        "space-2": "0.16px",
        "space-3": "0.18px",
        "space-4": "0.7px",
        "space-5": "0.96px",
        "space-6": "12px",
        "space-7": "30px"
      }
    }
  }
};
