/** Generated by DesignDNA — brand: revolut */
export const tokens = {
  "brand": "revolut",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "revolut-dark": "#191c1f",
    "pure-white": "#ffffff",
    "light-surface": "#f4f4f4",
    "revolut-blue": "#494fdf",
    "action-blue": "#4f55f1",
    "blue-text": "#376cd5",
    "danger-red": "#e23b4a",
    "deep-pink": "#e61e49",
    "warning-orange": "#ec7e00",
    "yellow": "#b09000",
    "teal": "#00a87e",
    "light-green": "#428619",
    "green-text": "#006400",
    "light-blue": "#007bc2",
    "brown": "#936d62",
    "red-text": "#8b0000",
    "mid-slate": "#505a63",
    "cool-gray": "#8d969e",
    "gray-tone": "#c9c9cd",
    "text": "#000000"
  },
  "typography": {
    "families": [
      "Blue Text",
      "Yellow",
      "Teal",
      "Green Text"
    ],
    "sizes": {
      "small": "20px"
    },
    "weights": [
      500
    ]
  },
  "spacing": {
    "space-1": "0.16px",
    "space-2": "2.72px",
    "space-3": "14px",
    "space-4": "20px",
    "space-5": "80px"
  },
  "radius": {
    "radius-1": "9999px",
    "radius-2": "12px"
  },
  "shadows": {}
} as const;

export type DesignTokens = typeof tokens;
