/** Generated by DesignDNA — brand: mistral.ai */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "mistral-orange": "#fa520f",
        "mistral-flame": "#fb6424",
        "block-orange": "#ff8105",
        "sunshine-900": "#ff8a00",
        "sunshine-700": "#ffa110",
        "sunshine-500": "#ffb83e",
        "sunshine-300": "#ffd06a",
        "block-gold": "#ffe295",
        "bright-yellow": "#ffd900",
        "warm-ivory": "#fffaeb",
        cream: "#fff0c2",
        "pure-white": "#ffffff",
        "mistral-black": "#1f1f1f"
      },
      fontFamily: {
        sans: [
          "Cream",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Primary",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Navigation",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Photography",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {},
      boxShadow: {},
      spacing: {
        "space-1": "2.05px",
        "space-2": "8px",
        "space-3": "12px",
        "space-4": "80px",
        "space-5": "82px"
      }
    }
  }
};
