/** Generated by DesignDNA — brand: uber */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "uber-black": "#000000",
        "pure-white": "#ffffff",
        "hover-gray": "#e2e2e2",
        "hover-light": "#f3f3f3",
        "chip-gray": "#efefef",
        "body-gray": "#4b4b4b",
        "muted-gray": "#afafaf",
        "default-link-blue": "#0000ee"
      },
      fontFamily: {
        sans: [
          "Navigation",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Hero",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Headings",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Footer",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {
        "radius-1": "999px",
        "radius-2": "8px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "10px",
        "space-2": "14px",
        "space-3": "32px",
        "space-4": "96px"
      }
    }
  }
};
