/** Generated by DesignDNA — brand: runwayml */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "runway-black": "#000000",
        "deep-black": "#030303",
        "dark-surface": "#1a1a1a",
        "pure-white": "#ffffff",
        "near-white": "#fefefe",
        "cool-cloud": "#e9ecf2",
        "border-dark": "#27272a",
        charcoal: "#404040",
        "near-charcoal": "#3f3f3f",
        "cool-slate": "#767d88",
        "mid-slate": "#7d848e",
        "muted-gray": "#a7a7a7",
        "cool-silver": "#c9ccd1",
        "light-silver": "#d0d4d4",
        "tailwind-gray": "#6b7280",
        "dark-link": "#0c0c0c",
        "footer-gray": "#999999"
      },
      fontFamily: {
        sans: [
          "switching",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "zero shadows",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "commitment",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Charcoal",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {},
      boxShadow: {},
      spacing: {
        "space-1": "0.35px",
        "space-2": "0.9px",
        "space-3": "1.2px",
        "space-4": "14px",
        "space-5": "24px",
        "space-6": "78px"
      }
    }
  }
};
