/** Generated by DesignDNA — brand: coinbase */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "coinbase-blue": "#0052ff",
        "pure-white": "#ffffff",
        "near-black": "#0a0b0d",
        "cool-gray-surface": "#eef0f3",
        "hover-blue": "#578bfa",
        "link-blue": "#0667d0",
        "muted-blue": "#5b616e",
        "dark-card": "#282b31"
      },
      fontFamily: {
        sans: [
          "Display",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Body",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Icons",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        large: "24px",
        xl: "40px"
      },
      borderRadius: {
        "radius-1": "56px",
        "radius-2": "8px"
      },
      boxShadow: {},
      spacing: {}
    }
  }
};
