/** Generated by DesignDNA — brand: cursor */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "cursor-dark": "#26251e",
        "cursor-cream": "#f2f1ed",
        "cursor-light": "#e6e5e0",
        "pure-white": "#ffffff",
        "true-black": "#000000",
        "cursor-orange": "#f54e00",
        gold: "#c08532",
        error: "#cf2d56",
        success: "#1f8a65",
        thinking: "#dfa88f",
        grep: "#9fc9a2",
        read: "#9fbbe0",
        edit: "#c0a8dd",
        "surface-100": "#f7f7f4",
        "surface-300": "#ebeae5",
        "surface-500": "#e1e0db"
      },
      fontFamily: {
        sans: [
          "Gold",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Error",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Success",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Thinking",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "72px"
      },
      borderRadius: {
        "radius-1": "8px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "0.11px",
        "space-2": "2.16px",
        "space-3": "3px",
        "space-4": "6px",
        "space-5": "8px",
        "space-6": "10px",
        "space-7": "14px",
        "space-8": "72px",
        "space-9": "80px",
        "space-10": "120px"
      }
    }
  }
};
