/** Generated by DesignDNA — brand: clickhouse */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "neon-volt": "#faff69",
        "forest-green": "#166534",
        "dark-forest": "#14572f",
        "pale-yellow": "#f4f692",
        "border-olive": "#4f5100",
        "olive-dark": "#161600",
        "pure-black": "#000000",
        "near-black": "#141414",
        charcoal: "#414141",
        "deep-charcoal": "#343434",
        "hover-gray": "#3a3a3a",
        "pure-white": "#ffffff",
        silver: "#a0a0a0",
        "mid-gray": "#585858",
        "border-gray": "#e5e7eb"
      },
      fontFamily: {
        sans: [
          "Charcoal",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Silver",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Primary",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Secondary Display",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {
        "radius-1": "4px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "1px",
        "space-2": "1.4px",
        "space-3": "4px",
        "space-4": "12px",
        "space-5": "64px"
      }
    }
  }
};
