/** Generated by DesignDNA — brand: clickhouse */
export const tokens = {
  "brand": "clickhouse",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "neon-volt": "#faff69",
    "forest-green": "#166534",
    "dark-forest": "#14572f",
    "pale-yellow": "#f4f692",
    "border-olive": "#4f5100",
    "olive-dark": "#161600",
    "pure-black": "#000000",
    "near-black": "#141414",
    "charcoal": "#414141",
    "deep-charcoal": "#343434",
    "hover-gray": "#3a3a3a",
    "pure-white": "#ffffff",
    "silver": "#a0a0a0",
    "mid-gray": "#585858",
    "border-gray": "#e5e7eb"
  },
  "typography": {
    "families": [
      "Charcoal",
      "Silver",
      "Primary",
      "Secondary Display"
    ],
    "sizes": {},
    "weights": [
      600,
      700,
      900
    ]
  },
  "spacing": {
    "space-1": "1px",
    "space-2": "1.4px",
    "space-3": "4px",
    "space-4": "12px",
    "space-5": "64px"
  },
  "radius": {
    "radius-1": "4px"
  },
  "shadows": {}
} as const;

export type DesignTokens = typeof tokens;
