/** Generated by DesignDNA — brand: spotify */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "spotify-green": "#1ed760",
        "near-black": "#121212",
        "dark-surface": "#181818",
        "mid-dark": "#1f1f1f",
        white: "#ffffff",
        silver: "#b3b3b3",
        "near-white": "#cbcbcb",
        light: "#fdfdfd",
        "negative-red": "#f3727f",
        "warning-orange": "#ffa42b",
        "announcement-blue": "#539df5",
        "dark-card": "#252525",
        "mid-card": "#272727",
        "border-gray": "#4d4d4d",
        "light-border": "#7c7c7c",
        "light-surface": "#eeeeee",
        "spotify-green-border": "#1db954"
      },
      fontFamily: {
        sans: [
          "White",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Silver",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Light",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Separator",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        large: "100px"
      },
      borderRadius: {
        "radius-1": "9999px",
        "radius-2": "500px",
        "radius-3": "6px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "1.4px",
        "space-2": "4px",
        "space-3": "8px",
        "space-4": "12px",
        "space-5": "14px"
      }
    }
  }
};
