/** Generated by DesignDNA — brand: renault */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "renault-yellow": "#efdf00",
        "absolute-black": "#000000",
        "pure-white": "#ffffff",
        "soft-yellow": "#f8eb4c",
        "renault-blue": "#1883fd",
        "warm-gray": "#d9d9d6",
        charcoal: "#222222",
        "pale-silver": "#f2f2f2",
        "border-gray": "#d1d1d1",
        "success-green": "#8dc572",
        "error-rose": "#be6464",
        "warning-amber": "#f0ad4e",
        "info-blue": "#337ab7"
      },
      fontFamily: {
        sans: [
          "features a distinctive",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "with 28-degree",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "NouvelR",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "besides NouvelR",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        large: "56px",
        caption: "12.8px"
      },
      borderRadius: {
        "radius-1": "0px",
        "radius-2": "50px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "6px",
        "space-2": "10px",
        "space-3": "24px",
        "space-4": "40px",
        "space-5": "80px"
      }
    }
  }
};
