/** Generated by DesignDNA — brand: superhuman */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "mysteria-purple": "#1b1938",
        "lavender-glow": "#cbb7fb",
        "charcoal-ink": "#292827",
        "amethyst-link": "#714cb6",
        "pure-white": "#ffffff",
        "warm-cream": "#e9e5dd",
        "parchment-border": "#dcd7d3"
      },
      fontFamily: {
        sans: [
          "Product UI",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Hover",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Mobile",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Scale",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        display: "48px"
      },
      borderRadius: {},
      boxShadow: {},
      spacing: {
        "space-1": "0.63px",
        "space-2": "1.32px",
        "space-3": "8px",
        "space-4": "16px",
        "space-5": "48px"
      }
    }
  }
};
