/** Generated by DesignDNA — brand: vercel */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "vercel-black": "#171717",
        "pure-white": "#ffffff",
        "true-black": "#000000",
        "ship-red": "#ff5b4f",
        "preview-pink": "#de1d8d",
        "develop-blue": "#0a72ef",
        "console-blue": "#0070f3",
        "console-purple": "#7928ca",
        "console-pink": "#eb367f",
        "link-blue": "#0072f5",
        "gray-600": "#4d4d4d",
        "gray-500": "#666666",
        "gray-400": "#808080",
        "gray-100": "#ebebeb",
        "gray-50": "#fafafa",
        "badge-blue-bg": "#ebf5ff",
        "badge-blue-text": "#0068d6"
      },
      fontFamily: {
        sans: [
          "Selection Text",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Primary",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Monospace",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        large: "64px",
        xl: "100px",
        display: "48px"
      },
      borderRadius: {
        "radius-1": "6px",
        "radius-2": "9999px",
        "radius-3": "64px",
        "radius-4": "8px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "0.96px",
        "space-2": "2.4px",
        "space-3": "8px",
        "space-4": "12px",
        "space-5": "16px",
        "space-6": "80px"
      }
    }
  }
};
