/** Generated by DesignDNA — brand: vercel */
export const tokens = {
  "brand": "vercel",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "vercel-black": "#171717",
    "pure-white": "#ffffff",
    "true-black": "#000000",
    "ship-red": "#ff5b4f",
    "preview-pink": "#de1d8d",
    "develop-blue": "#0a72ef",
    "console-blue": "#0070f3",
    "console-purple": "#7928ca",
    "console-pink": "#eb367f",
    "link-blue": "#0072f5",
    "gray-600": "#4d4d4d",
    "gray-500": "#666666",
    "gray-400": "#808080",
    "gray-100": "#ebebeb",
    "gray-50": "#fafafa",
    "badge-blue-bg": "#ebf5ff",
    "badge-blue-text": "#0068d6"
  },
  "typography": {
    "families": [
      "Selection Text",
      "Primary",
      "Monospace"
    ],
    "sizes": {
      "large": "64px",
      "xl": "100px",
      "display": "48px"
    },
    "weights": [
      400,
      500,
      600,
      700
    ]
  },
  "spacing": {
    "space-1": "0.96px",
    "space-2": "2.4px",
    "space-3": "8px",
    "space-4": "12px",
    "space-5": "16px",
    "space-6": "80px"
  },
  "radius": {
    "radius-1": "6px",
    "radius-2": "9999px",
    "radius-3": "64px",
    "radius-4": "8px"
  },
  "shadows": {}
} as const;

export type DesignTokens = typeof tokens;
