/** Generated by DesignDNA — brand: x.ai */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "pure-dark-theme": "#1f2228",
        "pure-white": "#ffffff",
        "color-1": "#000000"
      },
      fontFamily: {
        sans: [
          "in uppercase with tracked-out le",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "GeistMono 14px weight 400",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "universalSans 16px weight 400",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "GeistMono 12px uppercase",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {
        "radius-1": "0px"
      },
      boxShadow: {
        "shadow-1": "s anywhere on the site. Instead, depth is communicated through three mechanisms: (1) opacity-based borders that brighten on interaction, creating a sense of elements",
        "shadow-2": "s -- xAI has zero shadow elevation"
      },
      spacing: {
        "space-1": "1px",
        "space-2": "1.4px",
        "space-3": "4px",
        "space-4": "8px",
        "space-5": "12px",
        "space-6": "22px",
        "space-7": "48px",
        "space-8": "96px"
      }
    }
  }
};
