/** Generated by DesignDNA — brand: composio */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "composio-cobalt": "#0007cd",
        "electric-cyan": "#00ffff",
        "signal-blue": "#0089ff",
        "ocean-blue": "#0096ff",
        "void-black": "#0f0f0f",
        "pure-black": "#000000",
        charcoal: "#2c2c2c",
        "pure-white": "#ffffff",
        "muted-smoke": "#444444",
        "light-border": "#e0e0e0"
      },
      fontFamily: {
        sans: [
          "Charcoal",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Primary",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Monospace",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Navigation",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {},
      boxShadow: {},
      spacing: {
        "space-1": "0.28px",
        "space-2": "8px",
        "space-3": "10px",
        "space-4": "12px",
        "space-5": "32px",
        "space-6": "40px",
        "space-7": "120px"
      }
    }
  }
};
