/** Generated by DesignDNA — brand: composio */
export const tokens = {
  "brand": "composio",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "composio-cobalt": "#0007cd",
    "electric-cyan": "#00ffff",
    "signal-blue": "#0089ff",
    "ocean-blue": "#0096ff",
    "void-black": "#0f0f0f",
    "pure-black": "#000000",
    "charcoal": "#2c2c2c",
    "pure-white": "#ffffff",
    "muted-smoke": "#444444",
    "light-border": "#e0e0e0"
  },
  "typography": {
    "families": [
      "Charcoal",
      "Primary",
      "Monospace",
      "Navigation"
    ],
    "sizes": {},
    "weights": [
      400,
      500,
      700
    ]
  },
  "spacing": {
    "space-1": "0.28px",
    "space-2": "8px",
    "space-3": "10px",
    "space-4": "12px",
    "space-5": "32px",
    "space-6": "40px",
    "space-7": "120px"
  },
  "radius": {},
  "shadows": {}
} as const;

export type DesignTokens = typeof tokens;
