/** Generated by DesignDNA — brand: expo */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "expo-black": "#000000",
        "near-black": "#1c2024",
        "link-cobalt": "#0d74ce",
        "legal-blue": "#476cff",
        "widget-sky": "#47c2ff",
        "preview-purple": "#8145b5",
        "cloud-gray": "#f0f0f3",
        "pure-white": "#ffffff",
        "widget-dark": "#1a1a1a",
        "banner-dark": "#171717",
        "slate-gray": "#60646c",
        "mid-slate": "#555860",
        silver: "#b0b4ba",
        pewter: "#999999",
        "light-silver": "#cccccc",
        "dark-slate": "#363a3f",
        charcoal: "#333333",
        "warning-amber": "#ab6400",
        "destructive-rose": "#eb8e90",
        "border-lavender": "#e0e1e6",
        "input-border": "#d9d9e0",
        "dark-focus-ring": "#2547d0"
      },
      fontFamily: {
        sans: [
          "Silver",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Pewter",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Charcoal",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Primary",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "64px"
      },
      borderRadius: {},
      boxShadow: {},
      spacing: {
        "space-1": "0.25px",
        "space-2": "1.6px",
        "space-3": "3px",
        "space-4": "24px",
        "space-5": "32px",
        "space-6": "64px",
        "space-7": "96px"
      }
    }
  }
};
