/** Generated by DesignDNA — brand: wise */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "near-black": "#0e0f0c",
        "wise-green": "#9fe870",
        "dark-green": "#163300",
        "light-mint": "#e2f6d5",
        "pastel-green": "#cdffad",
        "positive-green": "#054d28",
        "danger-red": "#d03238",
        "warning-yellow": "#ffd11a",
        "bright-orange": "#ffc091",
        "warm-dark": "#454745",
        gray: "#868685",
        "light-surface": "#e8ebe6"
      },
      fontFamily: {
        sans: [
          "Gray",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Display",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        small: "30px",
        large: "30px"
      },
      borderRadius: {
        "radius-1": "9999px",
        "radius-2": "16px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "5px",
        "space-2": "8px"
      }
    }
  }
};
