/** Generated by DesignDNA — brand: lamborghini */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "lamborghini-gold": "#ffc000",
        "pure-white": "#ffffff",
        "dark-gold": "#917300",
        "gold-text": "#ffce3e",
        "cyan-pulse": "#29abe2",
        "link-blue": "#3860be",
        "absolute-black": "#000000",
        charcoal: "#202020",
        "dark-iron": "#181818",
        "near-white": "#f8f8f8",
        mist: "#e6e6e6",
        smoke: "#f5f5f5",
        graphite: "#494949",
        ash: "#7d7d7d",
        steel: "#969696",
        slate: "#666666",
        iron: "#555555",
        shadow: "#313131",
        "teal-action": "#1eaedb"
      },
      fontFamily: {
        sans: [
          "created by Character Type and de",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "carries hexagonal geometric DNA",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "by Character Type for Lamborghin",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "itself is so distinctive it does",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        display: "120px",
        large: "18px",
        small: "13px",
        caption: "14px"
      },
      borderRadius: {
        "radius-1": "0px",
        "radius-2": "20px",
        "radius-3": "2px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "5px",
        "space-2": "8px",
        "space-3": "14px",
        "space-4": "16px",
        "space-5": "24px",
        "space-6": "44px",
        "space-7": "56px"
      }
    }
  }
};
