/** Generated by DesignDNA — brand: spacex */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "space-black": "#000000",
        "spectral-white": "#f0f0fa"
      },
      fontFamily: {
        sans: [
          "with DIN heritage",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Display",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {
        "radius-1": "32px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "0.96px",
        "space-2": "1px",
        "space-3": "1.17px",
        "space-4": "18px"
      }
    }
  }
};
