/** Generated by DesignDNA — brand: spacex */
export const tokens = {
  "brand": "spacex",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "space-black": "#000000",
    "spectral-white": "#f0f0fa"
  },
  "typography": {
    "families": [
      "with DIN heritage",
      "Display"
    ],
    "sizes": {},
    "weights": [
      700
    ]
  },
  "spacing": {
    "space-1": "0.96px",
    "space-2": "1px",
    "space-3": "1.17px",
    "space-4": "18px"
  },
  "radius": {
    "radius-1": "32px"
  },
  "shadows": {}
} as const;

export type DesignTokens = typeof tokens;
