/** Generated by DesignDNA — brand: opencode.ai */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "opencode-dark": "#201d1d",
        "opencode-light": "#fdfcfc",
        "mid-gray": "#9a9898",
        "dark-surface": "#302c2c",
        "border-gray": "#646262",
        "light-surface": "#f1eeee",
        "accent-blue": "#007aff",
        "accent-blue-hover": "#0056b3",
        "accent-blue-active": "#004085",
        "danger-red": "#ff3b30",
        "danger-hover": "#d70015",
        "danger-active": "#a50011",
        "success-green": "#30d158",
        "warning-orange": "#ff9f0a",
        "warning-hover": "#cc7f08",
        "warning-active": "#995f06",
        "text-muted": "#6e6e73",
        "text-secondary": "#424245",
        background: "#f8f7f7"
      },
      fontFamily: {
        sans: [
          "Berkeley Mono",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Universal",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        body: "16px",
        caption: "14px"
      },
      borderRadius: {
        "radius-1": "4px",
        "radius-2": "6px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "4px",
        "space-2": "6px",
        "space-3": "8px",
        "space-4": "20px",
        "space-5": "96px"
      }
    }
  }
};
