/** Generated by DesignDNA — brand: together.ai */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "brand-magenta": "#ef2cc1",
        "brand-orange": "#fc4c02",
        "dark-blue": "#010120",
        "soft-lavender": "#bdbbff",
        "pure-white": "#ffffff",
        "pure-black": "#000000"
      },
      fontFamily: {
        sans: [
          "Primary",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Navigation",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {},
      borderRadius: {},
      boxShadow: {},
      spacing: {
        "space-1": "0.055px",
        "space-2": "0.16px",
        "space-3": "0.8px",
        "space-4": "1.92px",
        "space-5": "2px",
        "space-6": "32px",
        "space-7": "48px",
        "space-8": "120px"
      }
    }
  }
};
