/** Generated by DesignDNA — brand: together.ai */
export const tokens = {
  "brand": "together.ai",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "brand-magenta": "#ef2cc1",
    "brand-orange": "#fc4c02",
    "dark-blue": "#010120",
    "soft-lavender": "#bdbbff",
    "pure-white": "#ffffff",
    "pure-black": "#000000"
  },
  "typography": {
    "families": [
      "Primary",
      "Navigation"
    ],
    "sizes": {},
    "weights": [
      400,
      500
    ]
  },
  "spacing": {
    "space-1": "0.055px",
    "space-2": "0.16px",
    "space-3": "0.8px",
    "space-4": "1.92px",
    "space-5": "2px",
    "space-6": "32px",
    "space-7": "48px",
    "space-8": "120px"
  },
  "radius": {},
  "shadows": {}
} as const;

export type DesignTokens = typeof tokens;
