/** Generated by DesignDNA — brand: cal */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        charcoal: "#242424",
        midnight: "#111111",
        white: "#ffffff",
        "link-blue": "#0099ff",
        "focus-ring": "#3b82f6",
        "default-link": "#0000ee",
        "light-gray": "#f5f5f5",
        "mid-gray": "#898989",
        "pure-black": "#000000"
      },
      fontFamily: {
        sans: [
          "designed by Mark Davis",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Charcoal",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Midnight",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "White",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "64px",
        display: "36px"
      },
      borderRadius: {},
      boxShadow: {},
      spacing: {
        "space-1": "0.2px",
        "space-2": "4px",
        "space-3": "10px",
        "space-4": "12px",
        "space-5": "48px",
        "space-6": "80px"
      }
    }
  }
};
